### ISSUE TITLE
The config cant create 

### ISSUE THREAD

**Issue by antasetyawan** [Dans-Plugins/FoodSpoilage#190]
excuseme the config cant create proper, no config

**Comment by dmccoystephenson** [comment]
Hey thanks for letting us know! What version of the plugin are you using?

**Comment by antasetyawan** [comment]
latest version sir, im using 1.18.2

**Comment by dmccoystephenson** [comment]
Sorry to hear that! This will be fixed in the next release.

**Comment by dmccoystephenson** [comment]
This has been fixed.
