### ISSUE TITLE
Spoiled Fishing Items

### ISSUE THREAD

**Issue by ROB0520** [Dans-Plugins/FoodSpoilage#209]
Essentially when you fish for items **everything** has an expiry date, even stuff like books and tripwire hooks. It even turns spoiled after the date.
![image](https://user-images.githubusercontent.com/27846877/182314231-b56bb35e-d3fa-409c-8323-16f20d90fe03.png)

**Comment by dmccoystephenson** [comment]
Hey thanks for letting me know about this! I'll get this resolved soon.
